// Generated by gencpp from file test_serial_arduino/Connexion.msg
// DO NOT EDIT!


#ifndef TEST_SERIAL_ARDUINO_MESSAGE_CONNEXION_H
#define TEST_SERIAL_ARDUINO_MESSAGE_CONNEXION_H

#include <ros/service_traits.h>


#include <test_serial_arduino/ConnexionRequest.h>
#include <test_serial_arduino/ConnexionResponse.h>


namespace test_serial_arduino
{

struct Connexion
{

typedef ConnexionRequest Request;
typedef ConnexionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Connexion
} // namespace test_serial_arduino


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_serial_arduino::Connexion > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::test_serial_arduino::Connexion&) { return value(); }
};

template<>
struct DataType< ::test_serial_arduino::Connexion > {
  static const char* value()
  {
    return "test_serial_arduino/Connexion";
  }

  static const char* value(const ::test_serial_arduino::Connexion&) { return value(); }
};


// service_traits::MD5Sum< ::test_serial_arduino::ConnexionRequest> should match 
// service_traits::MD5Sum< ::test_serial_arduino::Connexion > 
template<>
struct MD5Sum< ::test_serial_arduino::ConnexionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_serial_arduino::Connexion >::value();
  }
  static const char* value(const ::test_serial_arduino::ConnexionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_serial_arduino::ConnexionRequest> should match 
// service_traits::DataType< ::test_serial_arduino::Connexion > 
template<>
struct DataType< ::test_serial_arduino::ConnexionRequest>
{
  static const char* value()
  {
    return DataType< ::test_serial_arduino::Connexion >::value();
  }
  static const char* value(const ::test_serial_arduino::ConnexionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_serial_arduino::ConnexionResponse> should match 
// service_traits::MD5Sum< ::test_serial_arduino::Connexion > 
template<>
struct MD5Sum< ::test_serial_arduino::ConnexionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_serial_arduino::Connexion >::value();
  }
  static const char* value(const ::test_serial_arduino::ConnexionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_serial_arduino::ConnexionResponse> should match 
// service_traits::DataType< ::test_serial_arduino::Connexion > 
template<>
struct DataType< ::test_serial_arduino::ConnexionResponse>
{
  static const char* value()
  {
    return DataType< ::test_serial_arduino::Connexion >::value();
  }
  static const char* value(const ::test_serial_arduino::ConnexionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SERIAL_ARDUINO_MESSAGE_CONNEXION_H
