// Generated by gencpp from file test_serial_arduino/DemandeContenantResponse.msg
// DO NOT EDIT!


#ifndef TEST_SERIAL_ARDUINO_MESSAGE_DEMANDECONTENANTRESPONSE_H
#define TEST_SERIAL_ARDUINO_MESSAGE_DEMANDECONTENANTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_serial_arduino
{
template <class ContainerAllocator>
struct DemandeContenantResponse_
{
  typedef DemandeContenantResponse_<ContainerAllocator> Type;

  DemandeContenantResponse_()
    : code(0)
    , success(false)  {
    }
  DemandeContenantResponse_(const ContainerAllocator& _alloc)
    : code(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int64_t _code_type;
  _code_type code;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DemandeContenantResponse_

typedef ::test_serial_arduino::DemandeContenantResponse_<std::allocator<void> > DemandeContenantResponse;

typedef boost::shared_ptr< ::test_serial_arduino::DemandeContenantResponse > DemandeContenantResponsePtr;
typedef boost::shared_ptr< ::test_serial_arduino::DemandeContenantResponse const> DemandeContenantResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_serial_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fba6e229d5c61f74155aa006ab7b7e3";
  }

  static const char* value(const ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fba6e229d5c61f7ULL;
  static const uint64_t static_value2 = 0x4155aa006ab7b7e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_serial_arduino/DemandeContenantResponse";
  }

  static const char* value(const ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 code\n\
bool success\n\
\n\
";
  }

  static const char* value(const ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DemandeContenantResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_serial_arduino::DemandeContenantResponse_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<int64_t>::stream(s, indent + "  ", v.code);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERIAL_ARDUINO_MESSAGE_DEMANDECONTENANTRESPONSE_H
