// Generated by gencpp from file test_serial_arduino/test.msg
// DO NOT EDIT!


#ifndef TEST_SERIAL_ARDUINO_MESSAGE_TEST_H
#define TEST_SERIAL_ARDUINO_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <test_serial_arduino/testRequest.h>
#include <test_serial_arduino/testResponse.h>


namespace test_serial_arduino
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace test_serial_arduino


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_serial_arduino::test > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::test_serial_arduino::test&) { return value(); }
};

template<>
struct DataType< ::test_serial_arduino::test > {
  static const char* value()
  {
    return "test_serial_arduino/test";
  }

  static const char* value(const ::test_serial_arduino::test&) { return value(); }
};


// service_traits::MD5Sum< ::test_serial_arduino::testRequest> should match 
// service_traits::MD5Sum< ::test_serial_arduino::test > 
template<>
struct MD5Sum< ::test_serial_arduino::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_serial_arduino::test >::value();
  }
  static const char* value(const ::test_serial_arduino::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_serial_arduino::testRequest> should match 
// service_traits::DataType< ::test_serial_arduino::test > 
template<>
struct DataType< ::test_serial_arduino::testRequest>
{
  static const char* value()
  {
    return DataType< ::test_serial_arduino::test >::value();
  }
  static const char* value(const ::test_serial_arduino::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_serial_arduino::testResponse> should match 
// service_traits::MD5Sum< ::test_serial_arduino::test > 
template<>
struct MD5Sum< ::test_serial_arduino::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_serial_arduino::test >::value();
  }
  static const char* value(const ::test_serial_arduino::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_serial_arduino::testResponse> should match 
// service_traits::DataType< ::test_serial_arduino::test > 
template<>
struct DataType< ::test_serial_arduino::testResponse>
{
  static const char* value()
  {
    return DataType< ::test_serial_arduino::test >::value();
  }
  static const char* value(const ::test_serial_arduino::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SERIAL_ARDUINO_MESSAGE_TEST_H
