// Generated by gencpp from file test_serial_arduino/testResponse.msg
// DO NOT EDIT!


#ifndef TEST_SERIAL_ARDUINO_MESSAGE_TESTRESPONSE_H
#define TEST_SERIAL_ARDUINO_MESSAGE_TESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_serial_arduino
{
template <class ContainerAllocator>
struct testResponse_
{
  typedef testResponse_<ContainerAllocator> Type;

  testResponse_()
    : sum(0)  {
    }
  testResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::test_serial_arduino::testResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_serial_arduino::testResponse_<ContainerAllocator> const> ConstPtr;

}; // struct testResponse_

typedef ::test_serial_arduino::testResponse_<std::allocator<void> > testResponse;

typedef boost::shared_ptr< ::test_serial_arduino::testResponse > testResponsePtr;
typedef boost::shared_ptr< ::test_serial_arduino::testResponse const> testResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_serial_arduino::testResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_serial_arduino::testResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_serial_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_serial_arduino::testResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_serial_arduino::testResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_serial_arduino::testResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_serial_arduino::testResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_serial_arduino::testResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_serial_arduino::testResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_serial_arduino::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::test_serial_arduino::testResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_serial_arduino::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_serial_arduino/testResponse";
  }

  static const char* value(const ::test_serial_arduino::testResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_serial_arduino::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n\
\n\
";
  }

  static const char* value(const ::test_serial_arduino::testResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_serial_arduino::testResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_serial_arduino::testResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_serial_arduino::testResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERIAL_ARDUINO_MESSAGE_TESTRESPONSE_H
