(cl:defpackage test_serial_arduino-srv
  (:use )
  (:export
   "CONNEXION"
   "<CONNEXION-REQUEST>"
   "CONNEXION-REQUEST"
   "<CONNEXION-RESPONSE>"
   "CONNEXION-RESPONSE"
   "DEMANDECONTENANT"
   "<DEMANDECONTENANT-REQUEST>"
   "DEMANDECONTENANT-REQUEST"
   "<DEMANDECONTENANT-RESPONSE>"
   "DEMANDECONTENANT-RESPONSE"
   "TEST"
   "<TEST-REQUEST>"
   "TEST-REQUEST"
   "<TEST-RESPONSE>"
   "TEST-RESPONSE"
  ))

